#include "Project.h"
#include "Theme.h"
#include <fstream>
#include <iostream>

namespace SkinningStudio {

Project::Project()
    : m_modified(false)
{
    New();
}

Project::~Project() = default;

void Project::New() {
    m_path = "";
    m_modified = false;
    m_root = std::make_unique<Panel>();
    m_root->SetName("Root");
    m_root->SetRect(Rect(0, 0, 800, 600));
    m_theme = Theme::CreateDefaultDarkTheme();
}

bool Project::Load(const std::string& path) {
    try {
        std::ifstream file(path);
        if (!file.is_open()) {
            std::cerr << "Failed to open project file: " << path << std::endl;
            return false;
        }
        
        nlohmann::json json;
        file >> json;
        file.close();
        
        if (DeserializeProject(json)) {
            m_path = path;
            m_modified = false;
            return true;
        }
    } catch (const std::exception& e) {
        std::cerr << "Error loading project: " << e.what() << std::endl;
    }
    return false;
}

bool Project::Save(const std::string& path) {
    try {
        nlohmann::json json = SerializeProject();
        
        std::ofstream file(path);
        if (!file.is_open()) {
            std::cerr << "Failed to save project file: " << path << std::endl;
            return false;
        }
        
        file << json.dump(2);
        file.close();
        
        m_path = path;
        m_modified = false;
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error saving project: " << e.what() << std::endl;
    }
    return false;
}

bool Project::Save() {
    if (m_path.empty()) {
        return false;
    }
    return Save(m_path);
}

void Project::SetRoot(std::unique_ptr<UIElement> root) {
    m_root = std::move(root);
    m_modified = true;
}

void Project::SetTheme(std::unique_ptr<Theme> theme) {
    m_theme = std::move(theme);
    m_modified = true;
}

bool Project::ImportTheme(const std::string& path) {
    try {
        std::ifstream file(path);
        if (!file.is_open()) {
            return false;
        }
        
        nlohmann::json json;
        file >> json;
        file.close();
        
        auto theme = std::make_unique<Theme>();
        theme->Deserialize(json);
        SetTheme(std::move(theme));
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error importing theme: " << e.what() << std::endl;
    }
    return false;
}

bool Project::ExportTheme(const std::string& path) {
    if (!m_theme) {
        return false;
    }
    
    try {
        nlohmann::json json = m_theme->Serialize();
        
        std::ofstream file(path);
        if (!file.is_open()) {
            return false;
        }
        
        file << json.dump(2);
        file.close();
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error exporting theme: " << e.what() << std::endl;
    }
    return false;
}

bool Project::ExportRuntimePackage(const std::string& directory) {
    try {
        // Export theme
        std::string themePath = directory + "/theme.json";
        if (!ExportTheme(themePath)) {
            std::cerr << "Failed to export theme" << std::endl;
            return false;
        }
        
        // Export layout
        std::string layoutPath = directory + "/ui_layout.json";
        std::ofstream layoutFile(layoutPath);
        if (!layoutFile.is_open()) {
            std::cerr << "Failed to create layout file" << std::endl;
            return false;
        }
        
        nlohmann::json layoutJson;
        if (m_root) {
            layoutJson = m_root->Serialize();
        }
        layoutFile << layoutJson.dump(2);
        layoutFile.close();
        
        // Export runtime sample
        std::string runtimePath = directory + "/runtime_sample.cpp";
        std::ofstream runtimeFile(runtimePath);
        if (!runtimeFile.is_open()) {
            std::cerr << "Failed to create runtime file" << std::endl;
            return false;
        }
        
        runtimeFile << R"(// Runtime Sample - Generated by SkinningStudio
#include <imgui.h>
#include <fstream>
#include <nlohmann/json.hpp>

// Load and render the exported UI
void RenderExportedUI() {
    // Load theme
    std::ifstream themeFile("theme.json");
    nlohmann::json theme;
    themeFile >> theme;
    
    // Load layout
    std::ifstream layoutFile("ui_layout.json");
    nlohmann::json layout;
    layoutFile >> layout;
    
    // Render UI elements based on loaded data
    // This is a simplified example
    ImGui::Begin("Exported UI");
    ImGui::Text("UI loaded from exported data");
    ImGui::End();
}
)";
        runtimeFile.close();
        
        std::cout << "Runtime package exported to: " << directory << std::endl;
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error exporting runtime package: " << e.what() << std::endl;
    }
    return false;
}

Project::ValidationResult Project::Validate() const {
    ValidationResult result;
    result.success = true;
    
    // Check for missing IDs
    // Check for duplicate IDs
    // Check for cyclic dependencies
    // Check for missing assets
    
    return result;
}

nlohmann::json Project::SerializeProject() const {
    nlohmann::json json;
    json["version"] = "1.0.0";
    
    if (m_root) {
        json["root"] = m_root->Serialize();
    }
    
    if (m_theme) {
        json["theme"] = m_theme->Serialize();
    }
    
    return json;
}

bool Project::DeserializeProject(const nlohmann::json& json) {
    try {
        if (!json.contains("version")) {
            std::cerr << "Project file missing version" << std::endl;
            return false;
        }
        
        if (json.contains("root")) {
            auto rootJson = json["root"];
            auto type = UIElement::TypeFromString(rootJson["type"]);
            m_root = UIElement::Create(type);
            m_root->Deserialize(rootJson);
        }
        
        if (json.contains("theme")) {
            m_theme = std::make_unique<Theme>();
            m_theme->Deserialize(json["theme"]);
        } else {
            m_theme = Theme::CreateDefaultDarkTheme();
        }
        
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error deserializing project: " << e.what() << std::endl;
    }
    return false;
}

} // namespace SkinningStudio
